export const truths = {
  romantic: [
    "Quel est le premier détail que tu as remarqué chez moi ?",
    "Quel est ton plus beau souvenir de nous deux ?",
    "Si notre histoire d'amour était un film, quel serait son titre ?",
    "Quelle est la chose la plus romantique que j'ai faite pour toi ?",
    "À quel moment as-tu su que tu étais amoureux/se de moi ?",
    "Quelle est la chanson qui te fait le plus penser à nous ?",
    "Décris le rendez-vous parfait avec moi.",
    "Quelle est la qualité que tu admires le plus chez moi ?",
    "Si tu devais décrire notre relation en un mot, lequel choisirais-tu ?",
    "Quel est le rêve le plus mémorable que tu aies fait de nous ?",
    "Quelle est la chose que je fais qui te fait fondre à chaque fois ?",
    "Si nous pouvions nous téléporter n'importe où pour un baiser, où irions-nous ?",
    "Quelle est la promesse que tu veux me faire pour notre futur ?",
    "Quel est le plus grand sacrifice que tu serais prêt(e) à faire pour moi ?",
    "Comment décrirais-tu la sensation de mon contact ?",
    "Quelle est la chose la plus folle que tu ferais par amour pour moi ?",
    "Si tu pouvais revivre un seul jour de notre relation, lequel serait-ce ?",
    "Qu'est-ce que j'ai apporté dans ta vie que personne d'autre n'a pu faire ?",
    "Quelle est la chose que tu as le plus hâte de faire avec moi à l'avenir ?",
    "Décris la première fois que nos regards se sont croisés.",
  ],
  hot: [
    "Quelle est la partie de mon corps que tu préfères ?",
    "Quel est ton plus grand fantasme me concernant ?",
    "Où aimerais-tu m'embrasser là, tout de suite ?",
    "Quelle est la chose la plus coquine que tu aimerais faire avec moi ?",
    "Décris le baiser le plus mémorable que nous ayons partagé.",
    "Quel est le vêtement que tu aimes le plus me voir porter (ou ne pas porter) ?",
    "Si tu pouvais me déshabiller avec les dents, par où commencerais-tu ?",
    "Murmure à l'oreille (virtuellement) ce que tu aimerais me faire ce soir.",
    "Quelle est la chose la plus osée que tu aies imaginée à mon sujet ?",
    "Si nous étions seuls sur une île déserte, quelle serait la première chose que tu me ferais ?",
    "Quel est le son que je fais que tu trouves le plus excitant ?",
    "Décris en détail ce que tu aimerais que je porte pour notre prochaine nuit ensemble.",
    "Quel est l'endroit le plus insolite où tu aimerais faire l'amour avec moi ?",
    "Si tu devais me donner un gage très coquin, quel serait-il ?",
    "Quelle est la chose que je fais qui t'excite le plus, même si c'est involontaire ?",
    "Comment aimes-tu être réveillé(e) le matin ?",
    "Quelle est ta position préférée ?",
    "Si tu pouvais goûter une partie de mon corps, laquelle choisirais-tu ?",
    "Quel est le film ou la scène qui t'a le plus donné envie de moi ?",
    "Raconte-moi un de tes rêves érotiques.",
  ],
  cute: [
    "Quel est le surnom le plus ridicule que tu m'aies secrètement donné ?",
    "Quelle est la chose la plus bizarre que tu aimes chez moi ?",
    "Si nous étions des animaux, quel couple d'animaux serions-nous ?",
    "Quelle est ta photo préférée de nous et pourquoi ?",
    "Imite ma tête quand je suis concentré(e).",
    "Quel est le plat que tu adores que je te cuisine ?",
    "Quelle est la manie que j'ai que tu trouves adorable ?",
    "Si on avait un animal de compagnie secret, quel serait-il et comment s'appellerait-il ?",
    "Quelle est la chose la plus enfantine que nous ayons faite ensemble ?",
    "Si j'étais une saveur de glace, laquelle serais-je ?",
    "Raconte une anecdote embarrassante mais mignonne à mon sujet.",
    "Quel est le message le plus mignon que tu aies gardé de moi ?",
    "Si on devait construire une cabane, à quoi ressemblerait-elle ?",
    "Quelle est la chose que je dis tout le temps et qui te fait sourire ?",
    "Imite ma danse de la victoire.",
    "Quel est le pyjama que tu préfères me voir porter ?",
  ],
};

export const dares = {
  romantic: [
    "Écris un poème de 3 lignes sur moi et lis-le à voix haute.",
    "Fais une déclaration d'amour sincère en 30 secondes.",
    "Envoie-moi la chanson qui décrit le mieux ce que tu ressens pour moi en ce moment.",
    "Change le fond d'écran de ton téléphone pour une photo de moi (ou de nous) pendant 24h.",
    "Fais un cœur avec tes mains et garde-le devant la caméra jusqu'à ton prochain tour.",
    "Raconte notre rencontre comme si c'était le début d'un conte de fées.",
    "Enregistre un mémo vocal disant 'Je t'aime' et envoie-le moi.",
    "Dessine notre futur maison de rêve et montre-la.",
    "Liste 5 choses que tu aimes dans notre relation.",
    "Fais semblant de me prendre dans tes bras et décris ce que tu ressens.",
    "Organise notre prochain rendez-vous (même à distance) et envoie-moi l'invitation.",
    "Mets une musique romantique et fais un slow tout(e) seul(e) en pensant à moi.",
    "Écris mon nom sur un papier, embrasse-le et montre-le à la caméra.",
    "Trouve la citation d'amour la plus belle et lis-la avec émotion.",
    "Fais-moi un compliment sur ma personnalité.",
  ],
  hot: [
    "Envoie une photo d'une partie de ton corps que tu sais que j'aime (sans montrer ton visage).",
    "Décris avec une voix sensuelle ce que tu portes en ce moment.",
    "Danse de manière sexy sur une musique de ton choix pendant 15 secondes.",
    "Lèche tes lèvres de la manière la plus lente et séduisante possible.",
    "Enlève un vêtement de ton choix.",
    "Fais-moi un strip-tease virtuel... avec tes mains.",
    "Prends une photo suggestive et envoie-la moi.",
    "Envoie un audio où tu chuchotes mon nom.",
    "Mets un glaçon sur une partie de ton corps et décris la sensation.",
    "Montre-moi comment tu m'embrasserais passionnément (sur ta main ou un oreiller).",
    "Prends une pose sexy et tiens-la pendant 10 secondes.",
    "Décris le massage que tu aimerais me faire en détail.",
    "Envoie une photo de tes lèvres.",
    "Fais semblant de déboutonner ta chemise très lentement.",
    "Dis-moi une chose que tu n'as jamais osé me demander de faire au lit.",
  ],
  cute: [
    "Fais un câlin à ton oreiller en m'appelant par un surnom mignon.",
    "Imite ton emoji préféré.",
    "Chante le refrain de la chanson la plus kitsch que tu connaisses.",
    "Fais ta meilleure imitation d'un animal qui essaie de séduire.",
    "Dessine-nous en bonhommes bâtons et montre ton œuvre d'art.",
    "Envoie un selfie avec la grimace la plus drôle que tu puisses faire.",
    "Construis un fort avec des couvertures et prends une photo depuis l'intérieur.",
    "Mets un filtre ridicule sur ton visage et fais une déclaration d'amour sérieuse.",
    "Parle avec une voix de dessin animé jusqu'à ton prochain tour.",
    "Essaie de jongler avec des objets que tu as sous la main.",
    "Fais une imitation de moi.",
    "Raconte une blague tellement nulle qu'elle en devient drôle.",
    "Porte un de tes vêtements à l'envers jusqu'à la fin du jeu.",
    "Fais une chorégraphie sur une musique de TikTok.",
    "Envoie une photo de tes chaussettes les plus ridicules.",
  ],
};

export const coupleQuiz = [
  { question: "Quelle est ma couleur préférée ?", options: ["Bleu", "Rouge", "Vert", "Noir"], answer: "Bleu" },
  { question: "Quel est mon film d'amour préféré ?", options: ["The Notebook", "Titanic", "La La Land", "Orgueil et Préjugés"], answer: "The Notebook" },
  { question: "Si je pouvais voyager n'importe où, où irais-je ?", options: ["Paris", "Tokyo", "Bali", "New York"], answer: "Bali" },
  { question: "Quel est mon plus grand rêve ?", options: ["Faire le tour du monde", "Écrire un livre", "Monter une entreprise", "Avoir une famille"], answer: "Faire le tour du monde" },
  { question: "Quelle est la première chose que je fais le matin ?", options: ["Regarder mon téléphone", "Boire un café", "Faire de l'exercice", "Prendre une douche"], answer: "Regarder mon téléphone" },
  { question: "Quel est mon plat préféré que tu cuisines ?", options: ["Pâtes Carbonara", "Poulet rôti", "Lasagnes", "Pizza maison"], answer: "Lasagnes" },
  { question: "De quoi ai-je le plus peur ?", options: ["Les araignées", "Le vide", "L'échec", "La solitude"], answer: "L'échec" },
  { question: "Le cadeau que je t'ai offert que tu as préféré ?", options: ["Un bijou", "Un voyage", "Un vêtement", "Un livre"], answer: "Un voyage" },
  { question: "Quelle est ma boisson préférée ?", options: ["Café", "Thé", "Jus d'orange", "Coca-Cola"], answer: "Thé" },
  { question: "Suis-je plutôt du matin ou du soir ?", options: ["Du matin", "Du soir"], answer: "Du soir" },
  { question: "Quel est mon talent caché ?", options: ["Chanter", "Dessiner", "Cuisiner", "Faire rire"], answer: "Dessiner" },
  { question: "Quelle est la série que je pourrais regarder en boucle ?", options: ["Friends", "Game of Thrones", "The Office", "Breaking Bad"], answer: "Friends" },
  { question: "Si j'étais un super-héros, quel serait mon pouvoir ?", options: ["Voler", "Invisibilité", "Téléportation", "Lire dans les pensées"], answer: "Téléportation" },
  { question: "Quelle est la destination de nos premières vacances ensemble ?", options: ["La plage", "La montagne", "Une grande ville", "La campagne"], answer: "La plage" },
  { question: "Quel est mon genre de musique préféré ?", options: ["Pop", "Rock", "Rap", "Électro"], answer: "Pop" },
  { question: "Comment s'appelait mon premier animal de compagnie ?", options: ["Max", "Bella", "Charlie", "Lucy"], answer: "Max" },
  { question: "Quel est le sport que je déteste le plus ?", options: ["Le football", "La course à pied", "Le yoga", "La natation"], answer: "La course à pied" },
  { question: "Quelle est ma plus grande qualité selon toi ?", options: ["Ma gentillesse", "Mon humour", "Mon intelligence", "Mon courage"], answer: "Ma gentillesse" },
  { question: "Quel est mon plus grand défaut selon toi ?", options: ["Je suis têtu(e)", "Je suis désordonné(e)", "Je suis impatient(e)", "Je suis jaloux/se"], answer: "Je suis têtu(e)" },
  { question: "Quel est le concert de nos rêves ?", options: ["Coldplay", "Beyoncé", "Ed Sheeran", "Daft Punk"], answer: "Coldplay" },
];

export const diceDares: { [key: number]: string[] } = {
  1: [
    "Fais un bisou à la caméra.",
    "Donne un compliment sur le physique de ton/ta partenaire.",
    "Envoie un emoji cœur.",
    "Raconte la première chose à laquelle tu as pensé en te réveillant ce matin.",
    "Fais un clin d'œil séducteur.",
  ],
  2: [
    "Raconte un court fantasme romantique.",
    "Chuchote quelque chose de doux à l'oreille de ton/ta partenaire (virtuellement).",
    "Prends une gorgée de ta boisson de manière sensuelle.",
    "Donne un surnom affectueux et original à ton/ta partenaire.",
    "Mets tes mains sur tes hanches et prends une pose de super-héros/héroïne de l'amour.",
  ],
  3: [
    "Enlève un accessoire (bijou, montre, etc.).",
    "Mords ta lèvre inférieure en regardant la caméra.",
    "Décris ton/ta partenaire en trois mots coquins.",
    "Fais semblant de frissonner en pensant à ton/ta partenaire.",
    "Envoie une photo de la vue que tu as en ce moment.",
  ],
  4: [
    "Fais un massage virtuel sur une partie du corps de ton/ta partenaire (décris-le).",
    "Envoie une photo d'un de tes sourires les plus charmeurs.",
    "Donne un gage 'Action ou Vérité' de la catégorie 'Hot' à ton/ta partenaire.",
    "Passe ta main dans tes cheveux de manière séduisante.",
    "Dis 'Tu me manques' avec la voix la plus triste possible.",
  ],
  5: [
    "Enlève un vêtement.",
    "Danse de manière lascive pendant 10 secondes.",
    "Raconte la chose la plus folle que tu aimerais faire avec ton/ta partenaire.",
    "Écris le prénom de ton/ta partenaire sur ton bras avec ton doigt.",
    "Fais un bisou sur une partie de ton corps que ton/ta partenaire aime.",
  ],
  6: [
    "Joker ! Tu peux inventer un gage pour ton/ta partenaire ou pour toi-même.",
    "Le perdant du prochain mini-jeu aura un double gage.",
    "Choisissez ensemble un gage de la liste 'Hot' à faire tous les deux.",
    "Carte 'Immunité' : tu peux refuser le prochain gage qui te sera donné.",
    "Échangez vos points dans le jeu en cours (si applicable).",
  ],
};

export const mysteryCardDares = [
  "Échange de rôle : tu dois imiter ton partenaire jusqu'à ton prochain tour.",
  "Vérité imposée : ton partenaire a le droit de te poser UNE question à laquelle tu dois répondre honnêtement.",
  "Action imposée : ton partenaire a le droit de te donner UN gage (raisonnable !).",
  "Carte 'Baiser Volé' : envoie un GIF de baiser à ton partenaire.",
  "Carte 'Sérénade' : chante les premières lignes de votre chanson.",
  "Carte 'Compliment Ultime' : fais le plus beau compliment que tu n'aies jamais fait à ton partenaire.",
  "Carte 'Secret' : avoue un petit secret mignon que ton partenaire ne connaît pas.",
  "Carte 'Main sur le cœur' : place ta main sur ton cœur et dis 'Je t'aime' en regardant la caméra.",
  "Carte 'Joker' : tu peux garder cette carte et l'utiliser pour passer ton tour plus tard.",
  "Carte 'Double Tour' : tu peux rejouer immédiatement.",
  "Carte 'Photomaton' : vous devez tous les deux prendre 4 selfies avec des expressions différentes (joyeux, triste, surpris, amoureux) et les envoyer.",
  "Carte 'Voyage dans le temps' : raconte ce que tu ferais si tu pouvais retourner au jour de notre rencontre.",
  "Carte 'Chef Cuisinier' : décris le plat parfait que tu cuisinerais pour ton/ta partenaire.",
  "Carte 'Poète d'un jour' : écris un haïku (5-7-5 syllabes) sur ton/ta partenaire.",
  "Carte 'Mime' : tu dois faire deviner un film d'amour à ton/ta partenaire en le mimant.",
  "Carte 'Confiance aveugle' : ferme les yeux et laisse ton/ta partenaire te guider verbalement pour trouver un objet dans ta pièce.",
  "Carte 'Playlist' : crée une playlist de 3 chansons pour ton/ta partenaire et partage-la.",
  "Carte 'Super pouvoir' : si tu avais un super pouvoir pour une journée pour ton/ta partenaire, que ferais-tu ?",
];

export const wouldYouRather = [
    { optionA: "Ne plus jamais manger de dessert", optionB: "Ne plus jamais manger de pizza" },
    { optionA: "Passer une soirée romantique à la maison", optionB: "Passer une soirée endiablée en ville" },
    { optionA: "Recevoir un long massage", optionB: "Faire un long massage" },
    { optionA: "Partir en vacances à la montagne", optionB: "Partir en vacances à la mer" },
    { optionA: "Savoir lire dans mes pensées", optionB: "Que je puisse lire dans les tiennes" },
    { optionA: "Un baiser passionné sous la pluie", optionB: "Un câlin tendre au coin du feu" },
    { optionA: "M'offrir un cadeau très cher", optionB: "M'organiser une surprise inoubliable" },
    { optionA: "Cuisiner ensemble", optionB: "Que l'un cuisine pour l'autre" },
    { optionA: "Vivre une aventure dangereuse ensemble", optionB: "Vivre une vie paisible et confortable ensemble" },
    { optionA: "Ne plus jamais avoir de secrets l'un pour l'autre", optionB: "Garder un petit jardin secret chacun" },
    { optionA: "Être incroyablement riche mais avoir moins de temps pour nous", optionB: "Avoir une vie simple mais beaucoup de temps ensemble" },
    { optionA: "Adopter 10 chiens", optionB: "Adopter 10 chats" },
    { optionA: "Regarder des films d'horreur ensemble", optionB: "Regarder des comédies romantiques ensemble" },
    { optionA: "Avoir une relation passionnelle et tumultueuse", optionB: "Avoir une relation calme et stable" },
    { optionA: "Communiquer uniquement par le regard", optionB: "Communiquer uniquement par le toucher" },
    { optionA: "Partir en road trip sans destination", optionB: "Partir dans un hôtel 5 étoiles tout compris" },
    { optionA: "Partager la même brosse à dents", optionB: "Partager le même compte en banque" },
    { optionA: "Affronter une armée de zombies ensemble", optionB: "Gagner à la loterie ensemble" },
    { optionA: "Ne plus jamais dire 'Je t'aime' mais le montrer", optionB: "Toujours dire 'Je t'aime' mais avoir du mal à le montrer" },
    { optionA: "Un amour de jeunesse qui dure toute la vie", optionB: "Une rencontre tardive mais fusionnelle" },
];
